-- DATABASE
CREATE DATABASE speedtracker;

-- SCHEMAS
CREATE SCHEMA speedtracker.tracker;

-- TABLES
CREATE TABLE tracker.speed_result (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ping_ms REAL NOT NULL,
    upload_mbps REAL NOT NULL,
    download_mbps REAL NOT NULL,
    server_name TEXT,
    server_location TEXT
);
COMMENT ON TABLE tracker.speed_result IS 'Stores results from the automated internet speed test.';

-- VIEWS
CREATE VIEW vw.speed_results 
AS 
	SELECT 
		ping_ms,
		upload_mbps,
		download_mbps,
		created_at AS result_time
	FROM tracker.speed_result
	ORDER BY created_at DESC

CREATE VIEW vw.speed_results_today 
AS 
	SELECT 
		ping_ms,
		upload_mbps,
		download_mbps,
		created_at AS result_time
	FROM tracker.speed_result
	WHERE
		created_at::DATE = NOW()::DATE
	ORDER BY created_at DESC